title: "MELT"
description: Documentation of the Matching and EvaLuation Toolkit (MELT).
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true

footer_content: "MELT Team 2021"

back_to_top: true
back_to_top_text: "Back to top"

exclude: ["javadoc_latest/"]