package de.uni_mannheim.informatik.dws.melt.matching_base;

/**
 * An AddNegatives matcher requires an ideally correct alignment as input to its match function (input alignment).
 * This input alignment can be (1) sampled from the reference or (2) generated by a high-precision matcher.
 */
public interface AddNegatives {
}
