call mvn clean test -P1
call mvn clean test -P2
call mvn clean test -P3
call mvn clean test -P4
call mvn clean test -P5
call mvn clean test -P6
call mvn clean test -P7
call mvn clean test -P8
call mvn clean test -P9
call mvn clean test -P10