name: Coveralls

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # this is required for the javadoc deploy plugin
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Print maven version
        run: mvn -version
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-1
      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}-1
      - name: Cache Transformers models
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/huggingface
          key: ${{ runner.os }}-transformers-models
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          # TODO: the latest pytorch version is only available for 3.9 and not yet in 3.10 - replace it with 3.x if it is available
          python-version: '3.11' 
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install python dependencies
        run: pip install -r ./matching-ml/src/main/resources/requirements.txt
      - name: Build with Maven and Run All Tests 📦🕵️
        run: mvn clean install
      - name: Coveralls
        run: mvn coveralls:report -DrepoToken=${{ secrets.COVERALLS }}